# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clay < Formula
  desc "CLAY IS A TOOL TO WORK WITH GO GO COMMAND REPOSITORIES"
  homepage "https://github.com/go-go-golems/clay"
  version "0.1.26"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/clay/releases/download/v0.1.26/clay_0.1.26_darwin_amd64.tar.gz"
      sha256 "d5e37afee20d50cbeb62e512196f467f2d87d6eefdf32feb380c7c349d1937c1"

      def install
        bin.install "clay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/clay/releases/download/v0.1.26/clay_0.1.26_darwin_arm64.tar.gz"
      sha256 "023668d4f8c101f77802e9c96cc8e03d3d539b1041faa4117fc5cebf3b892ec5"

      def install
        bin.install "clay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-go-golems/clay/releases/download/v0.1.26/clay_0.1.26_linux_amd64.tar.gz"
        sha256 "aa4388c0d004046023dc01ba4def67c57b206cea970619ce6ff0a7112789e776"

        def install
          bin.install "clay"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-go-golems/clay/releases/download/v0.1.26/clay_0.1.26_linux_arm64.tar.gz"
        sha256 "00722fab37522d38075823532063c86263e2805a4be24e75cf99fc08581cb844"

        def install
          bin.install "clay"
        end
      end
    end
  end
end
