# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cliopatra < Formula
  desc "cliopatra is a tool"
  homepage "https://github.com/go-go-golems/cliopatra"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/cliopatra/releases/download/v0.0.2/cliopatra_0.0.2_darwin_amd64.tar.gz"
      sha256 "f17154873f5b9a2b2a53a74414159c3fcb172d9379c89a0e6276da845b803920"

      def install
        bin.install "cliopatra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/cliopatra/releases/download/v0.0.2/cliopatra_0.0.2_darwin_arm64.tar.gz"
      sha256 "4c9d487d2279f395142db9898e31647d24f1ffae0aaf8fc08241647f6b15dec9"

      def install
        bin.install "cliopatra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/cliopatra/releases/download/v0.0.2/cliopatra_0.0.2_linux_arm64.tar.gz"
      sha256 "9eb9ef9e06348ef7291034787c4fc0accb8347e1b6547b10c54d669bce3c27ba"

      def install
        bin.install "cliopatra"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/cliopatra/releases/download/v0.0.2/cliopatra_0.0.2_linux_amd64.tar.gz"
      sha256 "8dbaa66935550b19aa6c146b013ad40d4c36db713214ca20201a07f78f526950"

      def install
        bin.install "cliopatra"
      end
    end
  end
end
