# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cliopatra < Formula
  desc "cliopatra is a tool"
  homepage "https://github.com/go-go-golems/cliopatra"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/cliopatra/releases/download/v0.1.0/cliopatra_0.1.0_darwin_amd64.tar.gz"
      sha256 "609f65d3a31701d124cec613748ab8a82cadadae6f9bd717b185d52077a92f93"

      def install
        bin.install "cliopatra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/cliopatra/releases/download/v0.1.0/cliopatra_0.1.0_darwin_arm64.tar.gz"
      sha256 "4c09aeb2db8a5e851a9c3dab48f2911326da8ef9d2972436af950757c1531e1d"

      def install
        bin.install "cliopatra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/cliopatra/releases/download/v0.1.0/cliopatra_0.1.0_linux_arm64.tar.gz"
      sha256 "5c8cc509a54da2483de91f23cf1f448a0376816fbd94d5a61cfc189ba2caf0a9"

      def install
        bin.install "cliopatra"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/cliopatra/releases/download/v0.1.0/cliopatra_0.1.0_linux_amd64.tar.gz"
      sha256 "ffabacb7507d91c8d09dfc898938133bb1db090d36381b4434eb068e55a4ec35"

      def install
        bin.install "cliopatra"
      end
    end
  end
end
