# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cliopatra < Formula
  desc "cliopatra is a tool"
  homepage "https://github.com/go-go-golems/cliopatra"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/cliopatra/releases/download/v0.0.1/cliopatra_0.0.1_darwin_amd64.tar.gz"
      sha256 "615440ff1487c62ca6efe689066c9ae152261b8135a1d50a80c71caca2f75e37"

      def install
        bin.install "cliopatra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/cliopatra/releases/download/v0.0.1/cliopatra_0.0.1_darwin_arm64.tar.gz"
      sha256 "e3924b15f70701e15f5861647c5edc7312259df127a554b5bbb4d94bf4e4d120"

      def install
        bin.install "cliopatra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/cliopatra/releases/download/v0.0.1/cliopatra_0.0.1_linux_arm64.tar.gz"
      sha256 "193c3d784a87098ea43e425fc42a6c12003b94b8c46cb9f9061e0b671d2c6e98"

      def install
        bin.install "cliopatra"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/cliopatra/releases/download/v0.0.1/cliopatra_0.0.1_linux_amd64.tar.gz"
      sha256 "a707b4c0918e22d26ceca75bb8073f1ae65619681a9acd28c2c19afc6b2e9cd4"

      def install
        bin.install "cliopatra"
      end
    end
  end
end
