# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cozo < Formula
  desc "cozo is a goja-based CLI for the CozoDB JavaScript API"
  homepage "https://github.com/go-go-golems/cozodb-goja"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/cozodb-goja/releases/download/v0.0.2/cozo_0.0.2_darwin_amd64.tar.gz"
      sha256 "7efa594c794b4bdea12cb98d0222c582babc92d89b67371dd132f61a15ff0b73"

      define_method(:install) do
        bin.install "cozo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/cozodb-goja/releases/download/v0.0.2/cozo_0.0.2_darwin_arm64.tar.gz"
      sha256 "577ad46bab7aaef4f8f44c9e7752518745f550a4fcb8dbe96e50764ce3da0ab4"

      define_method(:install) do
        bin.install "cozo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/cozodb-goja/releases/download/v0.0.2/cozo_0.0.2_linux_amd64.tar.gz"
      sha256 "b74a291661cb83a424b3e1daf6eefa96fd8b301f2fc59fda7d2758fda543375f"
      define_method(:install) do
        bin.install "cozo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/cozodb-goja/releases/download/v0.0.2/cozo_0.0.2_linux_arm64.tar.gz"
      sha256 "b7d3b689841b5a14ccfca81829f4e89a17ff97323fe1445531387364e92ee76d"
      define_method(:install) do
        bin.install "cozo"
      end
    end
  end
end
