# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CssVisualDiff < Formula
  desc "css-visual-diff compares rendered HTML/CSS across two browser targets."
  homepage "https://github.com/go-go-golems/css-visual-diff"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/css-visual-diff/releases/download/v0.1.5/css-visual-diff_0.1.5_darwin_amd64.tar.gz"
      sha256 "3234b593758976171f6828db5a7db2d74acfa939d61cd9aec32282944e9b17db"

      define_method(:install) do
        bin.install "css-visual-diff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/css-visual-diff/releases/download/v0.1.5/css-visual-diff_0.1.5_darwin_arm64.tar.gz"
      sha256 "737cf74ae7ddaad36782421758af199aa574ce9025286d16d620892edd3da270"

      define_method(:install) do
        bin.install "css-visual-diff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/css-visual-diff/releases/download/v0.1.5/css-visual-diff_0.1.5_linux_amd64.tar.gz"
      sha256 "6cb6fdb9502524ea20e53fd363828861ba4e8d8b03847836dd7476cf71d69010"
      define_method(:install) do
        bin.install "css-visual-diff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/css-visual-diff/releases/download/v0.1.5/css-visual-diff_0.1.5_linux_arm64.tar.gz"
      sha256 "06b7dd8fb0c20f1dbc7b5487a9ae9c2535843fec2069d49f3e739779a18120d7"
      define_method(:install) do
        bin.install "css-visual-diff"
      end
    end
  end
end
