# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CssVisualDiff < Formula
  desc "css-visual-diff compares rendered HTML/CSS across two browser targets."
  homepage "https://github.com/go-go-golems/css-visual-diff"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/css-visual-diff/releases/download/v0.0.1/css-visual-diff_0.0.1_darwin_amd64.tar.gz"
      sha256 "51c49b33e6d40cdc0250574a70c7dfe84d30e52e3c29ec90acda9363b679b8ae"

      define_method(:install) do
        bin.install "css-visual-diff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/css-visual-diff/releases/download/v0.0.1/css-visual-diff_0.0.1_darwin_arm64.tar.gz"
      sha256 "66b4a50bfb774bd8403e324a3d0cc1693979ec6f801d96669a60ecf245256be7"

      define_method(:install) do
        bin.install "css-visual-diff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/css-visual-diff/releases/download/v0.0.1/css-visual-diff_0.0.1_linux_amd64.tar.gz"
      sha256 "92e3436ebaeba3cd8b6280896a96802ae76a021ed7cf8d542955b5f42006fb3e"
      define_method(:install) do
        bin.install "css-visual-diff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/css-visual-diff/releases/download/v0.0.1/css-visual-diff_0.0.1_linux_arm64.tar.gz"
      sha256 "e5c5f866c2990f187db1d0ec79dcdf196d100d900ff838d5efe5721c2e0c7b74"
      define_method(:install) do
        bin.install "css-visual-diff"
      end
    end
  end
end
