# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devctl < Formula
  desc "devctl is a tool"
  homepage "https://github.com/go-go-golems/devctl"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/devctl/releases/download/v0.0.7/devctl_0.0.7_darwin_amd64.tar.gz"
      sha256 "22008ac889b029d30e3951707a5bf6086bff926df9d68dec4e223e1d063f06c3"

      define_method(:install) do
        bin.install "devctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/devctl/releases/download/v0.0.7/devctl_0.0.7_darwin_arm64.tar.gz"
      sha256 "5361883c717f9c510006f8cafbaaaffe121b8663c1b50f4d007c757a1519ae8d"

      define_method(:install) do
        bin.install "devctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/devctl/releases/download/v0.0.7/devctl_0.0.7_linux_amd64.tar.gz"
      sha256 "2cc5c48ff13e0b06b102e7786a5e5b7e2f646a0bdc87f8916dea4ccba6937fb9"
      define_method(:install) do
        bin.install "devctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/devctl/releases/download/v0.0.7/devctl_0.0.7_linux_arm64.tar.gz"
      sha256 "19d5bfe2440c3e1030560520e01a5a969b5d9eebb26e0fb682c28416806e3cc7"
      define_method(:install) do
        bin.install "devctl"
      end
    end
  end
end
