# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devctl < Formula
  desc "devctl is a tool"
  homepage "https://github.com/go-go-golems/devctl"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/devctl/releases/download/v0.0.6/devctl_0.0.6_darwin_amd64.tar.gz"
      sha256 "79f9cef38301ae826c34d4c263b9cbc86c943046f8886f5119586396a658ddfc"

      define_method(:install) do
        bin.install "devctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/devctl/releases/download/v0.0.6/devctl_0.0.6_darwin_arm64.tar.gz"
      sha256 "f4e0cdbdebe80de312594a15eaa00ad088b33f63dea048e89be3b7152d3232d1"

      define_method(:install) do
        bin.install "devctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/devctl/releases/download/v0.0.6/devctl_0.0.6_linux_amd64.tar.gz"
      sha256 "e621bad3717362949f74b1994fae78e0fea1a8707e6d8f73f83bd03d870e6817"
      define_method(:install) do
        bin.install "devctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/devctl/releases/download/v0.0.6/devctl_0.0.6_linux_arm64.tar.gz"
      sha256 "b636151a7906593246d78733a5d5532ce418bd82a01707fa6d69c37b14907cd9"
      define_method(:install) do
        bin.install "devctl"
      end
    end
  end
end
