# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devctl < Formula
  desc "devctl is a tool"
  homepage "https://github.com/go-go-golems/devctl"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/devctl/releases/download/v0.0.2/devctl_0.0.2_darwin_amd64.tar.gz"
      sha256 "589fb1cde6e2a384005ff9aacc92b95721460aa6d35a8c8fd3d482de709d8f8a"

      define_method(:install) do
        bin.install "devctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/devctl/releases/download/v0.0.2/devctl_0.0.2_darwin_arm64.tar.gz"
      sha256 "caf55e099c5748708a40a017d3e1babb5d2755621ea80febc71eadf2fc77228f"

      define_method(:install) do
        bin.install "devctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/devctl/releases/download/v0.0.2/devctl_0.0.2_linux_amd64.tar.gz"
      sha256 "0d37c03d144bd4d3646cce4cf8220c5f2d567a50868cd7e0c6d248a454dbc8fc"
      define_method(:install) do
        bin.install "devctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/devctl/releases/download/v0.0.2/devctl_0.0.2_linux_arm64.tar.gz"
      sha256 "dced9a08c62681921339844614ed9101985a96c2cbe24bc5aafeb1c8b837f424"
      define_method(:install) do
        bin.install "devctl"
      end
    end
  end
end
