# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DiscordBot < Formula
  desc "Go-hosted Discord bot runtime with a JavaScript authoring API"
  homepage "https://github.com/go-go-golems/discord-bot"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/discord-bot/releases/download/v0.1.0/discord-bot_0.1.0_darwin_amd64.tar.gz"
      sha256 "e7858c65b50c3db9fc09e7779f5761bbeb702467406a81a284b1b39b21a89cac"

      define_method(:install) do
        bin.install "discord-bot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/discord-bot/releases/download/v0.1.0/discord-bot_0.1.0_darwin_arm64.tar.gz"
      sha256 "71e8a5041087da2a0c790775e75a3b22de66c701ef8a8b7795e1894a9a29ceb6"

      define_method(:install) do
        bin.install "discord-bot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/discord-bot/releases/download/v0.1.0/discord-bot_0.1.0_linux_amd64.tar.gz"
      sha256 "9643d1fa08d5e24469600cba9fc749000c9a1c526cba36e821e22d6cfe5e7818"
      define_method(:install) do
        bin.install "discord-bot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/discord-bot/releases/download/v0.1.0/discord-bot_0.1.0_linux_arm64.tar.gz"
      sha256 "e4cdfe7b9c5fce6fc3100b6bca75b279d5e96de9a497cc1d96135c2b460a74f6"
      define_method(:install) do
        bin.install "discord-bot"
      end
    end
  end
end
