# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Docmgr < Formula
  desc "docmgr is a tool to manage documents when programming with LLMs"
  homepage "https://github.com/go-go-golems/docmgr"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/docmgr/releases/download/v0.0.5/docmgr_0.0.5_darwin_amd64.tar.gz"
      sha256 "c36b1c281f06c84218e0dac9676db20e368f7d626763655241317ddf135643ae"

      def install
        bin.install "docmgr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/docmgr/releases/download/v0.0.5/docmgr_0.0.5_darwin_arm64.tar.gz"
      sha256 "606b3912d5482a1ebb74ebe0c8c6513d50fc2286cf59af9fb9bee09ce028e203"

      def install
        bin.install "docmgr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/docmgr/releases/download/v0.0.5/docmgr_0.0.5_linux_amd64.tar.gz"
      sha256 "fbe30956bc8fa43fbe0ecac7ca7da5969534fc608b0cda9c4b7b596d9cbd96e8"
      def install
        bin.install "docmgr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/docmgr/releases/download/v0.0.5/docmgr_0.0.5_linux_arm64.tar.gz"
      sha256 "e6b26bc0d0812a8ce743d6eb9d3d393cbacef83b5c97de29d3dfbe6ddf3c8260"
      def install
        bin.install "docmgr"
      end
    end
  end
end
