# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Emrichen < Formula
  desc "emrichen is a go implementation of the template engine for YAML"
  homepage "https://github.com/go-go-golems/go-emrichen"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/go-emrichen/releases/download/v0.0.4/emrichen_0.0.4_darwin_amd64.tar.gz"
      sha256 "d9fe59f53e58f40142e765afc303baa0a5504ffa557ced3284ea57110bc0403e"

      def install
        bin.install "emrichen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/go-emrichen/releases/download/v0.0.4/emrichen_0.0.4_darwin_arm64.tar.gz"
      sha256 "c6e14610f81f1c60d1f9a364458cb9cfd162da7569d926cf095d621eeda72f2a"

      def install
        bin.install "emrichen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-go-golems/go-emrichen/releases/download/v0.0.4/emrichen_0.0.4_linux_amd64.tar.gz"
        sha256 "035cc9bb4354691dd07db4a1ba48097988b425c1e46a5a33af3327fc9ecb3c3b"

        def install
          bin.install "emrichen"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-go-golems/go-emrichen/releases/download/v0.0.4/emrichen_0.0.4_linux_arm64.tar.gz"
        sha256 "297a6519f1d7e6e7867fb11e344b772b6c187dd36da5c0f96869e16c6aa9cb67"

        def install
          bin.install "emrichen"
        end
      end
    end
  end
end
