# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EscuseMe < Formula
  desc "Escuse-me is a tool for querying elasticsearch"
  homepage "https://github.com/go-go-golems/escuse-me"
  version "0.2.21"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/escuse-me/releases/download/v0.2.21/escuse-me_0.2.21_darwin_amd64.tar.gz"
      sha256 "f3ee141b0dfb301d3c9de86787ec84ce9cd07e2296a82f78cd64383755717ab7"

      def install
        bin.install "escuse-me"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/escuse-me/releases/download/v0.2.21/escuse-me_0.2.21_darwin_arm64.tar.gz"
      sha256 "07d4a9bef4c54f7d07ba2023e6e2cf1c928aa2b4c59f5bc7d11579feefd9d237"

      def install
        bin.install "escuse-me"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-go-golems/escuse-me/releases/download/v0.2.21/escuse-me_0.2.21_linux_amd64.tar.gz"
        sha256 "3a1389de209dd774301abdf555dd07cd86394812c3154920b06d824f360de35f"

        def install
          bin.install "escuse-me"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-go-golems/escuse-me/releases/download/v0.2.21/escuse-me_0.2.21_linux_arm64.tar.gz"
        sha256 "6a7a9aca4a8d1677dfc724ad010b84f01feec43c02d7312759a39c49d2da7637"

        def install
          bin.install "escuse-me"
        end
      end
    end
  end
end
