# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glaze < Formula
  desc "Glaze is a tool for converting structured data"
  homepage "https://github.com/go-go-golems/glazed"
  version "0.2.68"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/glazed/releases/download/v0.2.68/glaze_0.2.68_darwin_amd64.tar.gz"
      sha256 "77f4a7fc2363406b7c9cab351d90d796ded6e83e4b8472a959f6cda8e7b54b83"

      def install
        bin.install "glaze"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/glazed/releases/download/v0.2.68/glaze_0.2.68_darwin_arm64.tar.gz"
      sha256 "ffe4ab1bbcf269b080fd442d176541bf27e9df68029c07403165d02a298d6242"

      def install
        bin.install "glaze"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/glazed/releases/download/v0.2.68/glaze_0.2.68_linux_arm64.tar.gz"
      sha256 "b522b1f2ece674b22a89559e58834fb229c75767da022377bd26830d4f8556ba"

      def install
        bin.install "glaze"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/glazed/releases/download/v0.2.68/glaze_0.2.68_linux_amd64.tar.gz"
      sha256 "39e9bbe28af3f66b538b59605684f4a289cd931f5511b1fa7173313c6bfe9f61"

      def install
        bin.install "glaze"
      end
    end
  end
end
