# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glaze < Formula
  desc "Glaze is a tool for converting structured data"
  homepage "https://github.com/go-go-golems/glazed"
  version "0.7.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/glazed/releases/download/v0.7.0/glaze_0.7.0_darwin_amd64.tar.gz"
      sha256 "27f6d0f92389bc5741f4f963e3aef07bdfe019fded9d9ae27ca1bd41c05dba6a"

      def install
        bin.install "glaze"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/glazed/releases/download/v0.7.0/glaze_0.7.0_darwin_arm64.tar.gz"
      sha256 "441939fd7d0d0acf8fa3bf45367d1eabb0e666159349c9615056af8c60329bd6"

      def install
        bin.install "glaze"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/glazed/releases/download/v0.7.0/glaze_0.7.0_linux_amd64.tar.gz"
      sha256 "600f5fe843200d6b6b6c2f87f91df371ec79635e0e069b0f3a78e713ff7e9085"
      def install
        bin.install "glaze"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/glazed/releases/download/v0.7.0/glaze_0.7.0_linux_arm64.tar.gz"
      sha256 "d22147aa604a19611d75b93e738a4d1a6affc019cb1ec11ff477a5ebd5c7a2ad"
      def install
        bin.install "glaze"
      end
    end
  end
end
