# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGoMcp < Formula
  desc "go-go-mcp is a tool to serve and run MCPs"
  homepage "https://github.com/go-go-golems/go-go-mcp"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/go-go-mcp/releases/download/v0.0.5/go-go-mcp_0.0.5_darwin_amd64.tar.gz"
      sha256 "611cdd7b534e85b5ce7e7b06178a773e088304d7900c4c61a6e635449a1287b1"

      def install
        bin.install "go-go-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/go-go-mcp/releases/download/v0.0.5/go-go-mcp_0.0.5_darwin_arm64.tar.gz"
      sha256 "dcc319454edb30f917ab73a671f3a0b9d5b3aaeec2bfd8d2ce19bced1a80daff"

      def install
        bin.install "go-go-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-go-golems/go-go-mcp/releases/download/v0.0.5/go-go-mcp_0.0.5_linux_amd64.tar.gz"
        sha256 "35ff6be4c7f6fefaf4c40cbab4876234246bc6caf8329a056c5a1bc0d044701f"

        def install
          bin.install "go-go-mcp"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-go-golems/go-go-mcp/releases/download/v0.0.5/go-go-mcp_0.0.5_linux_arm64.tar.gz"
        sha256 "12230e826d30c758d3baf5241ed0f213e998e0c56277b38acb2c4d64a8baee93"

        def install
          bin.install "go-go-mcp"
        end
      end
    end
  end
end
