# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGoAppArcAgi < Formula
  desc "go-go-app-arc-agi provides backend module integration for ARC-AGI."
  homepage "https://github.com/go-go-golems/go-go-app-arc-agi"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/go-go-app-arc-agi/releases/download/v0.0.1/go-go-app-arc-agi_0.0.1_darwin_amd64.tar.gz"
      sha256 "59e4c5d14a9377e1bed94fcad20d2c82b54135ed08ff6cbdf76f49792e1d0f15"

      define_method(:install) do
        bin.install "go-go-app-arc-agi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/go-go-app-arc-agi/releases/download/v0.0.1/go-go-app-arc-agi_0.0.1_darwin_arm64.tar.gz"
      sha256 "a7c8962125159e7a4ab06daf7926c875cfd019940919b4127332305a183371d2"

      define_method(:install) do
        bin.install "go-go-app-arc-agi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/go-go-app-arc-agi/releases/download/v0.0.1/go-go-app-arc-agi_0.0.1_linux_amd64.tar.gz"
      sha256 "660a824942663c12671bde0d3467c53a010a52a9059201c0387461f2a28e9fc8"
      define_method(:install) do
        bin.install "go-go-app-arc-agi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/go-go-app-arc-agi/releases/download/v0.0.1/go-go-app-arc-agi_0.0.1_linux_arm64.tar.gz"
      sha256 "a6460cae3e191eecadf1969022628c925c24b5fb4c7f596243747baff3798617"
      define_method(:install) do
        bin.install "go-go-app-arc-agi"
      end
    end
  end
end
