# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGoHost < Formula
  desc "go-go-host is a hosting platform control-plane CLI"
  homepage "https://github.com/go-go-golems/go-go-host"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/go-go-host/releases/download/v0.0.1/go-go-host_0.0.1_darwin_amd64.tar.gz"
      sha256 "901fd943287c3686d2f7315250aaaad89bde8c85282ab3215a5af2f8b8379887"

      define_method(:install) do
        bin.install "go-go-host"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/go-go-host/releases/download/v0.0.1/go-go-host_0.0.1_darwin_arm64.tar.gz"
      sha256 "f488ef1b5f47f9432a27579728e1b67c137b349a33dc781612260125bd04262c"

      define_method(:install) do
        bin.install "go-go-host"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/go-go-host/releases/download/v0.0.1/go-go-host_0.0.1_linux_amd64.tar.gz"
      sha256 "f0dfd39e79511cc5134371ec3f5bd520b08b62381504a7c913269bf96463965d"
      define_method(:install) do
        bin.install "go-go-host"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/go-go-host/releases/download/v0.0.1/go-go-host_0.0.1_linux_arm64.tar.gz"
      sha256 "96d5ff19f7b0ceb93b7a26c16316bd095bc47aad37e172bf7d280d867a517c00"
      define_method(:install) do
        bin.install "go-go-host"
      end
    end
  end
end
