# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGoAppArcAgi < Formula
  desc "go-go-app-arc-agi provides backend module integration for ARC-AGI."
  homepage "https://github.com/go-go-golems/go-go-app-arc-agi"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/go-go-app-arc-agi/releases/download/v0.0.2/go-go-app-arc-agi_0.0.2_darwin_amd64.tar.gz"
      sha256 "ecccbd2daf9beaed612a84a3617f1c4c731c24988d078dace3998a8b2a4d255d"

      define_method(:install) do
        bin.install "go-go-app-arc-agi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/go-go-app-arc-agi/releases/download/v0.0.2/go-go-app-arc-agi_0.0.2_darwin_arm64.tar.gz"
      sha256 "1acbaf92134b85aa0af56680292b489774ae7f82e3e1cca5042b2209b10fe67a"

      define_method(:install) do
        bin.install "go-go-app-arc-agi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/go-go-app-arc-agi/releases/download/v0.0.2/go-go-app-arc-agi_0.0.2_linux_amd64.tar.gz"
      sha256 "9970b4a3fcbd3e8797664f8c33aa945d9c034c55d397c2d388dee0b25c7a2f08"
      define_method(:install) do
        bin.install "go-go-app-arc-agi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/go-go-app-arc-agi/releases/download/v0.0.2/go-go-app-arc-agi_0.0.2_linux_arm64.tar.gz"
      sha256 "3ac8d11aa768233e8404aa67322ba6d09f92ecd92c8d9a2d6aa7a6f565643c96"
      define_method(:install) do
        bin.install "go-go-app-arc-agi"
      end
    end
  end
end
