# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGoLabs < Formula
  desc "go-go-labs contains experimental go go tools"
  homepage "https://github.com/go-go-golems/go-go-labs"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/go-go-labs/releases/download/v0.0.3/go-go-labs_0.0.3_darwin_amd64.tar.gz"
      sha256 "26885063b426cb3e75f8e2a25585ab1eaeb5f2f653bae2fa1347d9cf48dba60a"

      def install
        bin.install "mastoid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/go-go-labs/releases/download/v0.0.3/go-go-labs_0.0.3_darwin_arm64.tar.gz"
      sha256 "0ad3b046f00a43ac8561d8d92b1a28b0ae83ad812e3e550ad94d149d7f0003f6"

      def install
        bin.install "mastoid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/go-go-labs/releases/download/v0.0.3/go-go-labs_0.0.3_linux_arm64.tar.gz"
      sha256 "dda47963333d6c070bdbcd624a12db87602984e2daeb9e94b7cee33b6607d631"

      def install
        bin.install "mastoid"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/go-go-labs/releases/download/v0.0.3/go-go-labs_0.0.3_linux_amd64.tar.gz"
      sha256 "7cd0fa9b0d7715256eb1f5ff46857e5dd80a7f1305f3a58488f887cdb57b693e"

      def install
        bin.install "mastoid"
      end
    end
  end
end
