# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGoHost < Formula
  desc "go-go-host is a hosting platform control-plane CLI"
  homepage "https://github.com/go-go-golems/go-go-host"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/go-go-host/releases/download/v0.0.2/go-go-host_0.0.2_darwin_amd64.tar.gz"
      sha256 "1ace889a8c075455507cbfa5a16ac50e403ebc1cf426252eeb7e786e26010717"

      define_method(:install) do
        bin.install "go-go-host"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/go-go-host/releases/download/v0.0.2/go-go-host_0.0.2_darwin_arm64.tar.gz"
      sha256 "36395bbfca439a9e9798d715fac139a40e04c3bed82f656c555b7ff7d484980e"

      define_method(:install) do
        bin.install "go-go-host"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/go-go-host/releases/download/v0.0.2/go-go-host_0.0.2_linux_amd64.tar.gz"
      sha256 "4e4025806a828f837df37fadbe3e1e068fe6970ddf75671c7043ac91033840d9"
      define_method(:install) do
        bin.install "go-go-host"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/go-go-host/releases/download/v0.0.2/go-go-host_0.0.2_linux_arm64.tar.gz"
      sha256 "68f93481e78c856f2242d10e1c107b188047e7e277807338c3c6aa0f9f61315a"
      define_method(:install) do
        bin.install "go-go-host"
      end
    end
  end
end
