# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGoObjects < Formula
  desc "Durable Objects runtime for goja and xgoja"
  homepage "https://github.com/go-go-golems/go-go-objects"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/go-go-objects/releases/download/v0.0.2/go-go-objects_0.0.2_darwin_amd64.tar.gz"
      sha256 "d58eac772ccfcc856e345e26a41cc762270fef5f3689da6381247089e1ea5149"

      define_method(:install) do
        bin.install "go-go-objects"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/go-go-objects/releases/download/v0.0.2/go-go-objects_0.0.2_darwin_arm64.tar.gz"
      sha256 "1b55c5eebe0839ec8d83a3210e29fc37e2d6977e40c4212addffbd6c7d08ae94"

      define_method(:install) do
        bin.install "go-go-objects"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/go-go-objects/releases/download/v0.0.2/go-go-objects_0.0.2_linux_amd64.tar.gz"
      sha256 "9314b9e1ad4e004d9ce423cae0f11816efdbc744158826e73c2a37bad3fbe599"
      define_method(:install) do
        bin.install "go-go-objects"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/go-go-objects/releases/download/v0.0.2/go-go-objects_0.0.2_linux_arm64.tar.gz"
      sha256 "1663db91a39ae78cf96f0f22e2edf837a035eec7ae691d64209113ca56f4afa0"
      define_method(:install) do
        bin.install "go-go-objects"
      end
    end
  end
end
