# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGoOsBackend < Formula
  desc "Backend host contracts and lifecycle for go-go-os app modules"
  homepage "https://github.com/go-go-golems/go-go-os-backend"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/go-go-os-backend/releases/download/v0.0.2/go-go-os-backend_0.0.2_darwin_amd64.tar.gz"
      sha256 "230527f29e1835010a39d16f53588c73552d9f03b984cd58cda35b0c01a2c737"

      define_method(:install) do
        bin.install "go-go-os-backend"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/go-go-os-backend/releases/download/v0.0.2/go-go-os-backend_0.0.2_darwin_arm64.tar.gz"
      sha256 "f54e3759bfd80821688a96efa159119253eca4ebbf2a826eacf721e3260b29aa"

      define_method(:install) do
        bin.install "go-go-os-backend"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/go-go-os-backend/releases/download/v0.0.2/go-go-os-backend_0.0.2_linux_amd64.tar.gz"
      sha256 "e7285296aba562e3bffb28b6074f16892de5548e97ae5187d161d3b2f46a39a2"
      define_method(:install) do
        bin.install "go-go-os-backend"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/go-go-os-backend/releases/download/v0.0.2/go-go-os-backend_0.0.2_linux_arm64.tar.gz"
      sha256 "7a75da755aaf2f4a22b67a4b94197547daa6e660b1926b03319e06413159a4d4"
      define_method(:install) do
        bin.install "go-go-os-backend"
      end
    end
  end
end
