# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGoAppSqlite < Formula
  desc "go-go-app-sqlite is a sqlite launcher app"
  homepage "https://github.com/go-go-golems/go-go-app-sqlite"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/go-go-app-sqlite/releases/download/v0.0.1/go-go-app-sqlite_0.0.1_darwin_amd64.tar.gz"
      sha256 "4a84a4463edffd3526e0f2149b2f1a5b770bee62ec92247df903772b93c47086"

      define_method(:install) do
        bin.install "go-go-app-sqlite"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/go-go-app-sqlite/releases/download/v0.0.1/go-go-app-sqlite_0.0.1_darwin_arm64.tar.gz"
      sha256 "1eb95de04d12467f926fbd9ccec9f4306193da3dba48e44ff0ab4c6fe564f375"

      define_method(:install) do
        bin.install "go-go-app-sqlite"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/go-go-app-sqlite/releases/download/v0.0.1/go-go-app-sqlite_0.0.1_linux_amd64.tar.gz"
      sha256 "61d8107087247aa743321b4336b82d38d95d8d775f64b49f13e7634db33b3f30"
      define_method(:install) do
        bin.install "go-go-app-sqlite"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/go-go-app-sqlite/releases/download/v0.0.1/go-go-app-sqlite_0.0.1_linux_arm64.tar.gz"
      sha256 "106f3a8c291b37a957e5adb9e22235e848f159607d9f1bc92e0f2ae3c97d50d6"
      define_method(:install) do
        bin.install "go-go-app-sqlite"
      end
    end
  end
end
