# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoMinitrace < Formula
  desc "Glazed-based Go port of minitrace, focused first on Claude Code and Codex session conversion."
  homepage "https://github.com/go-go-golems/go-minitrace"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/go-minitrace/releases/download/v0.0.2/go-minitrace_0.0.2_darwin_amd64.tar.gz"
      sha256 "cba2a2ae93f88849fe5458a85c57081fe82d70ab4a5f63bc33a5fc402c4832f7"

      define_method(:install) do
        bin.install "go-minitrace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/go-minitrace/releases/download/v0.0.2/go-minitrace_0.0.2_darwin_arm64.tar.gz"
      sha256 "77209c1e74b943aedd9288f588f71b03a73938ba77b4a5323f15f1185f51d708"

      define_method(:install) do
        bin.install "go-minitrace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/go-minitrace/releases/download/v0.0.2/go-minitrace_0.0.2_linux_amd64.tar.gz"
      sha256 "3626e832899ca6454cd28475970eeebddef840719b575df263912dd4c86d2bf6"
      define_method(:install) do
        bin.install "go-minitrace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/go-minitrace/releases/download/v0.0.2/go-minitrace_0.0.2_linux_arm64.tar.gz"
      sha256 "fa515da94a127c7e26c220249ae9c93f8da85c7155fa043be0acc1f0ae51b0c7"
      define_method(:install) do
        bin.install "go-minitrace"
      end
    end
  end
end
