# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GojaBleve < Formula
  desc "goja-bleve is a tool"
  homepage "https://github.com/go-go-golems/goja-bleve"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/goja-bleve/releases/download/v0.0.5/goja-bleve_0.0.5_darwin_amd64.tar.gz"
      sha256 "c4c32353c504c1038fe082c0ac553e58cd9900552b221eba239a44c0d369c310"

      define_method(:install) do
        bin.install "goja-bleve"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/goja-bleve/releases/download/v0.0.5/goja-bleve_0.0.5_darwin_arm64.tar.gz"
      sha256 "2b1fd48b81eccd913ea29a0336612ebe5af0b9bba02a93827e186f00baf0c026"

      define_method(:install) do
        bin.install "goja-bleve"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/goja-bleve/releases/download/v0.0.5/goja-bleve_0.0.5_linux_amd64.tar.gz"
      sha256 "4df560ea8aff6776693c2d530f4bf664cdc6cd86a9015b350f3a897af21216c4"
      define_method(:install) do
        bin.install "goja-bleve"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/goja-bleve/releases/download/v0.0.5/goja-bleve_0.0.5_linux_arm64.tar.gz"
      sha256 "24b4e1554a56ea1e6f14799c03abfe6b47901ee49a8669e8366dd62f74a2ccfb"
      define_method(:install) do
        bin.install "goja-bleve"
      end
    end
  end
end
