# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GojaGha < Formula
  desc "Run GitHub Actions-oriented JavaScript on top of Goja"
  homepage "https://github.com/go-go-golems/goja-github-actions"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/goja-github-actions/releases/download/v0.0.1/goja-github-actions_0.0.1_darwin_amd64.tar.gz"
      sha256 "da3d19809fedfef6359f2b012086820618702b72493098eaa56050a89e6a91b1"

      define_method(:install) do
        bin.install "goja-gha"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/goja-github-actions/releases/download/v0.0.1/goja-github-actions_0.0.1_darwin_arm64.tar.gz"
      sha256 "c1eb1e7962ec96f131d05ee47b6b59d20cf605a1ec4c5fed87dac734e27c5a26"

      define_method(:install) do
        bin.install "goja-gha"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/goja-github-actions/releases/download/v0.0.1/goja-github-actions_0.0.1_linux_amd64.tar.gz"
      sha256 "c6f2ec97ba1dea5ad75efa214d98415c13727a8918265e0dabc60fa67c122593"
      define_method(:install) do
        bin.install "goja-gha"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/goja-github-actions/releases/download/v0.0.1/goja-github-actions_0.0.1_linux_arm64.tar.gz"
      sha256 "9ab6e1010db16fcdfab937db311188f99b91f463ac4036aac547a216c0560318"
      define_method(:install) do
        bin.install "goja-gha"
      end
    end
  end
end
