# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GojaBleve < Formula
  desc "goja-bleve is a tool"
  homepage "https://github.com/go-go-golems/goja-bleve"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/goja-bleve/releases/download/v0.0.6/goja-bleve_0.0.6_darwin_amd64.tar.gz"
      sha256 "8c5c2569e37291824c58b4a5c184c76e00a4b124d15621a26ee4e972bbae6637"

      define_method(:install) do
        bin.install "goja-bleve"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/goja-bleve/releases/download/v0.0.6/goja-bleve_0.0.6_darwin_arm64.tar.gz"
      sha256 "c76d60a02cf43d9df4b89b052f2ccff54bd6f906bc1c6d0c968fd164c7ec22f8"

      define_method(:install) do
        bin.install "goja-bleve"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/goja-bleve/releases/download/v0.0.6/goja-bleve_0.0.6_linux_amd64.tar.gz"
      sha256 "0d3e64ec2b60d50f2190a3ba539dc6d7f17a86dc667ec7aac0214020a1b92420"
      define_method(:install) do
        bin.install "goja-bleve"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/goja-bleve/releases/download/v0.0.6/goja-bleve_0.0.6_linux_arm64.tar.gz"
      sha256 "c5f16283af660d76c28b9008befe0162258b1fad7c959ba16f59c0ec29235ab2"
      define_method(:install) do
        bin.install "goja-bleve"
      end
    end
  end
end
