# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GojaGha < Formula
  desc "Run GitHub Actions-oriented JavaScript on top of Goja"
  homepage "https://github.com/go-go-golems/goja-github-actions"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/goja-github-actions/releases/download/v0.0.2/goja-github-actions_0.0.2_darwin_amd64.tar.gz"
      sha256 "5b94d196058cc50351227d886becb2adc67ce75247e14f4b57aca3991d84d2ef"

      define_method(:install) do
        bin.install "goja-gha"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/goja-github-actions/releases/download/v0.0.2/goja-github-actions_0.0.2_darwin_arm64.tar.gz"
      sha256 "8017dc0d1f8937841b6fe709a62e5a19e7360b0019ca2ecc14008498191b7f32"

      define_method(:install) do
        bin.install "goja-gha"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/goja-github-actions/releases/download/v0.0.2/goja-github-actions_0.0.2_linux_amd64.tar.gz"
      sha256 "628e8845b8482a9706a5de6239636ce5afb77295cda8bcba70a8e97ae679f6c5"
      define_method(:install) do
        bin.install "goja-gha"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/goja-github-actions/releases/download/v0.0.2/goja-github-actions_0.0.2_linux_arm64.tar.gz"
      sha256 "97cb92889f48f7c48d16925b58af08bcad17cbf9e49b4bff92229ed31b435ee4"
      define_method(:install) do
        bin.install "goja-gha"
      end
    end
  end
end
