# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GojaText < Formula
  desc "goja-text provides Go-backed xgoja text modules and helper commands."
  homepage "https://github.com/go-go-golems/goja-text"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/goja-text/releases/download/v0.0.7/goja-text_0.0.7_darwin_amd64.tar.gz"
      sha256 "6bcec978b742dfc7b6c230221ada0b3858b1ae3a08c9ae512600a3d734451cb2"

      define_method(:install) do
        bin.install "goja-text"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/goja-text/releases/download/v0.0.7/goja-text_0.0.7_darwin_arm64.tar.gz"
      sha256 "b986e98e5f18ccfe03b165ccad12e552801321d294261e49a35a1d5a24d824f2"

      define_method(:install) do
        bin.install "goja-text"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/goja-text/releases/download/v0.0.7/goja-text_0.0.7_linux_amd64.tar.gz"
      sha256 "df35c9eb235b450cd7f4cecf8838cf301ac812e2d3d303d762cafba021af3742"
      define_method(:install) do
        bin.install "goja-text"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/goja-text/releases/download/v0.0.7/goja-text_0.0.7_linux_arm64.tar.gz"
      sha256 "f4c9c11dc83165fc1b9a8fc3c9e275cb87097846133f0a1fbfae490b0068f512"
      define_method(:install) do
        bin.install "goja-text"
      end
    end
  end
end
