# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GojaGit < Formula
  desc "Run JavaScript scripts with Git bindings"
  homepage "https://github.com/go-go-golems/goja-git"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/goja-git/releases/download/v0.1.1/goja-git_0.1.1_darwin_amd64.tar.gz"
      sha256 "3e112aadcf317800ad1db0ee06e6e2028e75bcfbcda979502de5e4cb2b9adcd1"

      define_method(:install) do
        bin.install "goja-git"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/goja-git/releases/download/v0.1.1/goja-git_0.1.1_darwin_arm64.tar.gz"
      sha256 "2aeddf558d4f5e9dfb60a9312ea404cdd52162522c4b930e3f6c63fbbc28cef3"

      define_method(:install) do
        bin.install "goja-git"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/goja-git/releases/download/v0.1.1/goja-git_0.1.1_linux_amd64.tar.gz"
      sha256 "4fb668e2bf15eebcae89a79ef9d8c96dd80b208840393b8563c4ff966914cc42"
      define_method(:install) do
        bin.install "goja-git"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/goja-git/releases/download/v0.1.1/goja-git_0.1.1_linux_arm64.tar.gz"
      sha256 "e1e75bba457f401456f731d235caaec6bc57b3032def9b2783b8227711a7a7ab"
      define_method(:install) do
        bin.install "goja-git"
      end
    end
  end
end
