# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LlmProxyServer < Formula
  desc "llm-proxy-server exposes OpenAI-compatible chat and completions endpoints backed by Geppetto profiles"
  homepage "https://github.com/go-go-golems/llm-proxy"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/llm-proxy/releases/download/v0.0.1/llm-proxy_0.0.1_darwin_amd64.tar.gz"
      sha256 "0e925ab983901741d11e4bcaefaf34c796389ae4f0db797aa9effcf6947d024f"

      define_method(:install) do
        bin.install "llm-proxy-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/llm-proxy/releases/download/v0.0.1/llm-proxy_0.0.1_darwin_arm64.tar.gz"
      sha256 "8950a6416fca72722a4479813ac71df2f7cb5925a4cab4a0072e1348e5191edf"

      define_method(:install) do
        bin.install "llm-proxy-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/llm-proxy/releases/download/v0.0.1/llm-proxy_0.0.1_linux_amd64.tar.gz"
      sha256 "0e9944e1b71fa03592ae97e61c476d76a1a916e294f6db2e277e38a37ccc65b9"
      define_method(:install) do
        bin.install "llm-proxy-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/llm-proxy/releases/download/v0.0.1/llm-proxy_0.0.1_linux_arm64.tar.gz"
      sha256 "2c7d17267dc5bb5bad916d05014a6443d74bad3ad4e78572fba5945a881f5b54"
      define_method(:install) do
        bin.install "llm-proxy-server"
      end
    end
  end
end
