# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LogcopterGen < Formula
  desc "logcopter-gen is a tool"
  homepage "https://github.com/go-go-golems/logcopter"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/logcopter/releases/download/v0.1.1/logcopter-gen_0.1.1_darwin_amd64.tar.gz"
      sha256 "a4947e7f69d86af7faeafdb7d6292109a5cec82b2a26b650caba0520b3b215ca"

      define_method(:install) do
        bin.install "logcopter-gen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/logcopter/releases/download/v0.1.1/logcopter-gen_0.1.1_darwin_arm64.tar.gz"
      sha256 "ae8ef02b7b5dac43644e89e1978da6628283f93c9d9a0d440a01f442137070c4"

      define_method(:install) do
        bin.install "logcopter-gen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/logcopter/releases/download/v0.1.1/logcopter-gen_0.1.1_linux_amd64.tar.gz"
      sha256 "a53fb6666574d85c8e00a8612bbb51eb340963768aba187eb59485acbd151ffb"
      define_method(:install) do
        bin.install "logcopter-gen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/logcopter/releases/download/v0.1.1/logcopter-gen_0.1.1_linux_arm64.tar.gz"
      sha256 "7f69283cf94339e3852f210278f2f32b5292d4986760ac6529ac64bc2861ec64"
      define_method(:install) do
        bin.install "logcopter-gen"
      end
    end
  end
end
