# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LogcopterGen < Formula
  desc "logcopter-gen is a tool"
  homepage "https://github.com/go-go-golems/logcopter"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/logcopter/releases/download/v0.0.1/logcopter-gen_0.0.1_darwin_amd64.tar.gz"
      sha256 "c409f662cf705a129888969af2d194b72efd38bdedab9bfbd9795bdd37adbee8"

      define_method(:install) do
        bin.install "logcopter-gen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/logcopter/releases/download/v0.0.1/logcopter-gen_0.0.1_darwin_arm64.tar.gz"
      sha256 "a4930b1caf8d81f61d3e8cb30e78e66d4d61e662e30b9c874fea3e4e16a83e9c"

      define_method(:install) do
        bin.install "logcopter-gen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/logcopter/releases/download/v0.0.1/logcopter-gen_0.0.1_linux_amd64.tar.gz"
      sha256 "a060bccba5bd7a23f59a4e0f01380b8f94fedac0625a93a17045b819b2f89fe4"
      define_method(:install) do
        bin.install "logcopter-gen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/logcopter/releases/download/v0.0.1/logcopter-gen_0.0.1_linux_arm64.tar.gz"
      sha256 "445e2b4f5877780964825173cb1a6ad546c57b36d74d4d80c49b11e6509f35ed"
      define_method(:install) do
        bin.install "logcopter-gen"
      end
    end
  end
end
