# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mastoid < Formula
  desc "mastoid is a tool"
  homepage "https://github.com/go-go-golems/mastoid"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/mastoid/releases/download/v0.0.1/mastoid_0.0.1_darwin_amd64.tar.gz"
      sha256 "06464098cdfcb9afd503ebc80f5cb0d2f73699f0b1a1a4a93f825a1804460173"

      def install
        bin.install "mastoid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/mastoid/releases/download/v0.0.1/mastoid_0.0.1_darwin_arm64.tar.gz"
      sha256 "80d44e522d52b85ecf85651d3c6edfed8591aeb9aa3917e0b7db1578d9b72291"

      def install
        bin.install "mastoid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/mastoid/releases/download/v0.0.1/mastoid_0.0.1_linux_amd64.tar.gz"
      sha256 "ed709bf4bc758a989b4563a9ad6f5e95d1b8f1f7a01902a0e61801d0327d08d1"

      def install
        bin.install "mastoid"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/mastoid/releases/download/v0.0.1/mastoid_0.0.1_linux_arm64.tar.gz"
      sha256 "e4441e20aad39ca26119391c942d02771c68d0b0eb578f6f9fdad8f4f579d668"

      def install
        bin.install "mastoid"
      end
    end
  end
end
