# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcp < Formula
  desc "mcp is a tool to serve and run MCPs"
  homepage "https://github.com/go-go-golems/go-go-mcp"
  version "0.0.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/go-go-mcp/releases/download/v0.0.11/mcp_0.0.11_darwin_amd64.tar.gz"
      sha256 "2b0b32681bf11e87daa0f8e4fabf9a042665755219db3293e943f1f898bd3c1c"

      def install
        bin.install "mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/go-go-mcp/releases/download/v0.0.11/mcp_0.0.11_darwin_arm64.tar.gz"
      sha256 "13d6b3febf93d62409f93d9584d4ae14fecb16e2c8ad7e804eb5a09372d9c5cb"

      def install
        bin.install "mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/go-go-mcp/releases/download/v0.0.11/mcp_0.0.11_linux_amd64.tar.gz"
      sha256 "2d90b1c09d19c56f77fadb5b7fded336a12dec109b598f44ac5e6b7e640fca88"
      def install
        bin.install "mcp"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/go-go-mcp/releases/download/v0.0.11/mcp_0.0.11_linux_arm64.tar.gz"
      sha256 "a9e33e41a3e42de8330a04ef7a59337abff3dc79e73f55cf67990f689fc9b25a"
      def install
        bin.install "mcp"
      end
    end
  end
end
