# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcp < Formula
  desc "mcp is a tool to serve and run MCPs"
  homepage "https://github.com/go-go-golems/go-go-mcp"
  version "0.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/go-go-mcp/releases/download/v0.0.9/mcp_0.0.9_darwin_amd64.tar.gz"
      sha256 "afda5963ceba396da61ea1293f7fc98ec86569ad40bdb81408958c2fb3044d3b"

      def install
        bin.install "mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/go-go-mcp/releases/download/v0.0.9/mcp_0.0.9_darwin_arm64.tar.gz"
      sha256 "889bfe50ed2d8c25c8f9a240081c223ec539a633f29e6fa518d21a062f5ed317"

      def install
        bin.install "mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/go-go-mcp/releases/download/v0.0.9/mcp_0.0.9_linux_amd64.tar.gz"
      sha256 "15431c39a0641904bfdf748ea507bbd4db2856fc4d75a2584df9a8692a959c91"
      def install
        bin.install "mcp"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/go-go-mcp/releases/download/v0.0.9/mcp_0.0.9_linux_arm64.tar.gz"
      sha256 "c5970931404acf70ef506f11e823d1fcce8c984c2e791e28a4bf9bb45cc92569"
      def install
        bin.install "mcp"
      end
    end
  end
end
