# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcp < Formula
  desc "mcp is a tool to serve and run MCPs"
  homepage "https://github.com/go-go-golems/go-go-mcp"
  version "0.0.15"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/go-go-mcp/releases/download/v0.0.15/mcp_0.0.15_darwin_amd64.tar.gz"
      sha256 "221186ed8d09bb308412b24648e8b601d7211652613b2d9b47e8cda1e817990c"

      def install
        bin.install "mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/go-go-mcp/releases/download/v0.0.15/mcp_0.0.15_darwin_arm64.tar.gz"
      sha256 "8c371b25925358949b54b433c965228a68bcb766db2367f7485f2ed5c17b2ea4"

      def install
        bin.install "mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/go-go-mcp/releases/download/v0.0.15/mcp_0.0.15_linux_amd64.tar.gz"
      sha256 "367a1e014785f06eacadeeb51b446816db24f4c65748c6f3432900e602f24084"
      def install
        bin.install "mcp"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/go-go-mcp/releases/download/v0.0.15/mcp_0.0.15_linux_arm64.tar.gz"
      sha256 "aea0ffc89a967f33a7b17eacdd171ea1a027f801ddebc048e3c6b3f6213c2e37"
      def install
        bin.install "mcp"
      end
    end
  end
end
