# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpenaiMockServer < Formula
  desc "OpenAI-compatible mock server for development and testing"
  homepage "https://github.com/go-go-golems/openai-mock-server"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/openai-mock-server/releases/download/v0.0.1/openai-mock-server_0.0.1_darwin_amd64.tar.gz"
      sha256 "8ba0ae6fdb84f56c2ca772bed1c49338c4f7235e79538a6842e436b71ddba1f5"

      def install
        bin.install "openai-mock-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/openai-mock-server/releases/download/v0.0.1/openai-mock-server_0.0.1_darwin_arm64.tar.gz"
      sha256 "277eccd55ebd1de3672938d4c0d6c374bb9dfd4df16739adf57e6df3a6a84512"

      def install
        bin.install "openai-mock-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/openai-mock-server/releases/download/v0.0.1/openai-mock-server_0.0.1_linux_amd64.tar.gz"
      sha256 "2e918deaa1ac3fe5042b4c4ec8031c6e2e6484dff6aca0de52a775480b6c2d4d"
      def install
        bin.install "openai-mock-server"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/openai-mock-server/releases/download/v0.0.1/openai-mock-server_0.0.1_linux_arm64.tar.gz"
      sha256 "51e61c734b50cfaf52644bdc8caa9b2a36b88e4aeaab9804ba949b1d61ec494d"
      def install
        bin.install "openai-mock-server"
      end
    end
  end
end
