# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlzConfirm < Formula
  desc "plz-confirm is a tool"
  homepage "https://github.com/go-go-golems/plz-confirm"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/plz-confirm/releases/download/v0.0.2/plz-confirm_0.0.2_darwin_amd64.tar.gz"
      sha256 "ec8ba6e6ce73edb8203e1554122824ee764bc73dec175c3b0a2de1ac904bf645"

      def install
        bin.install "plz-confirm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/plz-confirm/releases/download/v0.0.2/plz-confirm_0.0.2_darwin_arm64.tar.gz"
      sha256 "f637eacdb61431e0d2e03c45b0a44553f822b8bf6dec1c90641cf4dea92346ca"

      def install
        bin.install "plz-confirm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/plz-confirm/releases/download/v0.0.2/plz-confirm_0.0.2_linux_amd64.tar.gz"
      sha256 "537ccdea270d8baf7bd82351a274579d5d33da29081b138ef58a033aabc5170b"
      def install
        bin.install "plz-confirm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/plz-confirm/releases/download/v0.0.2/plz-confirm_0.0.2_linux_arm64.tar.gz"
      sha256 "c7b1eb6cfa24106da17243e60eb55f4e57fb1d35d4dea3298eac90bb68b3e705"
      def install
        bin.install "plz-confirm"
      end
    end
  end
end
