# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlzConfirm < Formula
  desc "plz-confirm is a tool"
  homepage "https://github.com/go-go-golems/plz-confirm"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/plz-confirm/releases/download/v0.0.3/plz-confirm_0.0.3_darwin_amd64.tar.gz"
      sha256 "e61b2d04b9cd01c751dfbd87ddb659008d7b3347c0d5493000e1ba96acdc2588"

      def install
        bin.install "plz-confirm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/plz-confirm/releases/download/v0.0.3/plz-confirm_0.0.3_darwin_arm64.tar.gz"
      sha256 "97a727be6104d3926ca9da9b247680c340df70b3f605c5a5bb65cdbdebf407b0"

      def install
        bin.install "plz-confirm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/plz-confirm/releases/download/v0.0.3/plz-confirm_0.0.3_linux_amd64.tar.gz"
      sha256 "4e153fceb87dd2f1e5eed36e6da26ac0d9b32fa364f6d890f6b36f3cf8b0244d"
      def install
        bin.install "plz-confirm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/plz-confirm/releases/download/v0.0.3/plz-confirm_0.0.3_linux_arm64.tar.gz"
      sha256 "41529419718e2518bd5ff2f49e193dedccc1c384bb901e98706dbc33ef438c5d"
      def install
        bin.install "plz-confirm"
      end
    end
  end
end
