# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prescribe < Formula
  desc "Prescribe is a CLI/TUI application for generating pull request descriptions using AI"
  homepage "https://github.com/go-go-golems/prescribe"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/prescribe/releases/download/v0.0.3/prescribe_0.0.3_darwin_amd64.tar.gz"
      sha256 "bb6e8cd9f6871ef635e460878aa0ed1011adf0b40befd9247fe89c4e3b236b31"

      def install
        bin.install "prescribe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/prescribe/releases/download/v0.0.3/prescribe_0.0.3_darwin_arm64.tar.gz"
      sha256 "ac1cf3da3a685e07bc580517ac713f74d7ddfd7de241d6a9f9a747c021102a93"

      def install
        bin.install "prescribe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/prescribe/releases/download/v0.0.3/prescribe_0.0.3_linux_amd64.tar.gz"
      sha256 "98a5dc164f8793b4c018de4ffdd40cd64b531fd8e727faacdc1575a8656d4258"
      def install
        bin.install "prescribe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/prescribe/releases/download/v0.0.3/prescribe_0.0.3_linux_arm64.tar.gz"
      sha256 "4cd398cb7c195e2a348f469cc1f01eea79e7f9d33617b54990f5d85f2949257c"
      def install
        bin.install "prescribe"
      end
    end
  end
end
