# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prescribe < Formula
  desc "Prescribe is a CLI/TUI application for generating pull request descriptions using AI"
  homepage "https://github.com/go-go-golems/prescribe"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/prescribe/releases/download/v0.0.1/prescribe_0.0.1_darwin_amd64.tar.gz"
      sha256 "11a914d5504998fb92aeb98227459aa14fda8076111aae775c2e470c2fa54aa9"

      def install
        bin.install "prescribe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/prescribe/releases/download/v0.0.1/prescribe_0.0.1_darwin_arm64.tar.gz"
      sha256 "de9124a016de52bf0b6faabbc4e38022d4229663fa14c10af0e28ba2ef3ccca2"

      def install
        bin.install "prescribe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/prescribe/releases/download/v0.0.1/prescribe_0.0.1_linux_amd64.tar.gz"
      sha256 "2a4681deb66d4f6485af5414d009068f256e37bc3322510ca428b54ac4303ab1"
      def install
        bin.install "prescribe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/prescribe/releases/download/v0.0.1/prescribe_0.0.1_linux_arm64.tar.gz"
      sha256 "48baa0e263e3461d20afa665662989488cfb1619cd2c5ec4106958c47ad3b527"
      def install
        bin.install "prescribe"
      end
    end
  end
end
