# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prompto < Formula
  desc "prompto is a tool"
  homepage "https://github.com/go-go-golems/XXX"
  version "0.1.13"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/prompto/releases/download/v0.1.13/prompto_0.1.13_darwin_amd64.tar.gz"
      sha256 "3f6a9968f38fdf716aba2d916bdd9bf8456b4dd13e3bb3b45d66c05f5f40d393"

      def install
        bin.install "prompto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/prompto/releases/download/v0.1.13/prompto_0.1.13_darwin_arm64.tar.gz"
      sha256 "a59c9d4fdf94e7ab3640ba90fcec151348320ef8ecc0e345e7893a6bcbb9afbe"

      def install
        bin.install "prompto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/prompto/releases/download/v0.1.13/prompto_0.1.13_linux_amd64.tar.gz"
      sha256 "65a4a776b9bfc327fc7c1c35295fcb3d51aa5719620705002c2181970278f207"
      def install
        bin.install "prompto"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/prompto/releases/download/v0.1.13/prompto_0.1.13_linux_arm64.tar.gz"
      sha256 "87d331cbd0b9a69a495e6dcf85bb9e3376654598f05be59a419071533935141b"
      def install
        bin.install "prompto"
      end
    end
  end
end
