# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Researchctl < Formula
  desc "researchctl manages research projects as typed claim/evidence/decision graphs"
  homepage "https://github.com/go-go-golems/researchctl"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/researchctl/releases/download/v0.0.3/researchctl_0.0.3_darwin_amd64.tar.gz"
      sha256 "01632f0e0ef6ce71706d84ca5900bbbb2e93c2cdda9b45e90f4fa330d42bc92f"

      define_method(:install) do
        bin.install "researchctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/researchctl/releases/download/v0.0.3/researchctl_0.0.3_darwin_arm64.tar.gz"
      sha256 "873017990c2d7fb108563c259e4d60b50d9d5dc6cc38d0408908a04571586b0c"

      define_method(:install) do
        bin.install "researchctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/researchctl/releases/download/v0.0.3/researchctl_0.0.3_linux_amd64.tar.gz"
      sha256 "2a6c96039b4de7779fcae201f87f842275820f28cdee665444d8e054eef2cfcc"
      define_method(:install) do
        bin.install "researchctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/researchctl/releases/download/v0.0.3/researchctl_0.0.3_linux_arm64.tar.gz"
      sha256 "cafaad1f6a338b04ea666234fab2033bca730c56ccb3adcfc9c6226cb8e64107"
      define_method(:install) do
        bin.install "researchctl"
      end
    end
  end
end
