# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sanitize < Formula
  desc "YAML sanitizer — lint and heuristically fix common YAML errors"
  homepage "https://github.com/go-go-golems/sanitize"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/sanitize/releases/download/v0.0.1/sanitize_0.0.1_darwin_amd64.tar.gz"
      sha256 "00a9593d8d6acfaeb9db78cc36ee2b6b3866a5943d81c50af0b8033774f664a9"

      define_method(:install) do
        bin.install "sanitize"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/sanitize/releases/download/v0.0.1/sanitize_0.0.1_darwin_arm64.tar.gz"
      sha256 "35379b0af35063cb747368d387bd25b47367f2c3e9746c86f8744e34df2de11d"

      define_method(:install) do
        bin.install "sanitize"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/sanitize/releases/download/v0.0.1/sanitize_0.0.1_linux_amd64.tar.gz"
      sha256 "4fa5bc4d0714a60f74708aa5de51bbc2f4a2e0870a746bac4e00578b64de2ffc"
      define_method(:install) do
        bin.install "sanitize"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/sanitize/releases/download/v0.0.1/sanitize_0.0.1_linux_arm64.tar.gz"
      sha256 "14074babe76de464ef504666f64219ebe58f2afd243537a36be52eaa198de99f"
      define_method(:install) do
        bin.install "sanitize"
      end
    end
  end
end
