# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scraper < Formula
  desc "scraper is a tool"
  homepage "https://github.com/go-go-golems/scraper"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/scraper/releases/download/v0.0.1/scraper_0.0.1_darwin_amd64.tar.gz"
      sha256 "7ed3b3f046ae33ceb4a5ba4e2ac79f99d96fb60f15094ac4d8384ce0f0e9bf1e"

      define_method(:install) do
        bin.install "scraper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/scraper/releases/download/v0.0.1/scraper_0.0.1_darwin_arm64.tar.gz"
      sha256 "f708a0def5880945ce3cd2a1b6e496d16adf22557e6c961752807879f2d42249"

      define_method(:install) do
        bin.install "scraper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/scraper/releases/download/v0.0.1/scraper_0.0.1_linux_amd64.tar.gz"
      sha256 "85284348ce080fc6383cdde6a6e30ac397a055f4b402f5326673d7021119064c"
      define_method(:install) do
        bin.install "scraper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/scraper/releases/download/v0.0.1/scraper_0.0.1_linux_arm64.tar.gz"
      sha256 "eafd38918b13acefbb590c0bec2c0bc26e1eda3a62ef77594cd64b70e5841b7c"
      define_method(:install) do
        bin.install "scraper"
      end
    end
  end
end
