# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scraper < Formula
  desc "scraper is a tool"
  homepage "https://github.com/go-go-golems/scraper"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/scraper/releases/download/v0.0.2/scraper_0.0.2_darwin_amd64.tar.gz"
      sha256 "a0d067a6fba1f4515bf08e92b27320b48a314b3766f6a1a37f454bff8416a1f4"

      define_method(:install) do
        bin.install "scraper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/scraper/releases/download/v0.0.2/scraper_0.0.2_darwin_arm64.tar.gz"
      sha256 "13f3eb37d63ee6117db1173cc9533aced7523b4ac362727adc58e437b7d84608"

      define_method(:install) do
        bin.install "scraper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/scraper/releases/download/v0.0.2/scraper_0.0.2_linux_amd64.tar.gz"
      sha256 "9649020af2432ed9eeda0da16929b4a1505f1cab340e0ce8d7c450f18d486fe0"
      define_method(:install) do
        bin.install "scraper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/scraper/releases/download/v0.0.2/scraper_0.0.2_linux_arm64.tar.gz"
      sha256 "9d4105bdd2344688bc0bedb4bbcd78e3826024a7bb36d71429d263f5446b3329"
      define_method(:install) do
        bin.install "scraper"
      end
    end
  end
end
