# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scraper < Formula
  desc "scraper is a tool"
  homepage "https://github.com/go-go-golems/scraper"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/scraper/releases/download/v0.0.3/scraper_0.0.3_darwin_amd64.tar.gz"
      sha256 "cd39260074d66f93a70071064f4b199c7ca3bf9c376bf0780a4e2ac1bede600f"

      define_method(:install) do
        bin.install "scraper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/scraper/releases/download/v0.0.3/scraper_0.0.3_darwin_arm64.tar.gz"
      sha256 "3e69936b55d5fb95f3ca3a0093a48e2be03684668c115eeaa71d043ebc6ba343"

      define_method(:install) do
        bin.install "scraper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/scraper/releases/download/v0.0.3/scraper_0.0.3_linux_amd64.tar.gz"
      sha256 "5db0d25967ba21aff8afbef5a65a7660273f271a624448ff9747e0a47da61cea"
      define_method(:install) do
        bin.install "scraper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/scraper/releases/download/v0.0.3/scraper_0.0.3_linux_arm64.tar.gz"
      sha256 "879715da0fc53255b53f533a62b54a3223447cd1c3efc5daec6c5175e5bd96a6"
      define_method(:install) do
        bin.install "scraper"
      end
    end
  end
end
