# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sqleton < Formula
  desc "Sqleton is a tool for querying databases"
  homepage "https://github.com/go-go-golems/sqleton"
  version "0.1.52"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/sqleton/releases/download/v0.1.52/sqleton_0.1.52_darwin_amd64.tar.gz"
      sha256 "fc20e43c9641d6bc28dff8f6443d754996ae5779508d1978cbed29d2074fb76f"

      def install
        bin.install "sqleton"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/sqleton/releases/download/v0.1.52/sqleton_0.1.52_darwin_arm64.tar.gz"
      sha256 "dcc7db3eb9a35fea58d3490cd3370056ec86047da3a18be58610e9d3c239075a"

      def install
        bin.install "sqleton"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/sqleton/releases/download/v0.1.52/sqleton_0.1.52_linux_arm64.tar.gz"
      sha256 "1302f315c4908cf31ceabb515f8666dcd3166526095865f023f120c2469c177b"

      def install
        bin.install "sqleton"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/sqleton/releases/download/v0.1.52/sqleton_0.1.52_linux_amd64.tar.gz"
      sha256 "1c1829dc20a734fc069ba310017360d82e75220541002f4d1a9aaef149c5f120"

      def install
        bin.install "sqleton"
      end
    end
  end
end
