# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tactician < Formula
  desc "tactician is a tool"
  homepage "https://github.com/go-go-golems/tactician"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/tactician/releases/download/v0.0.1/tactician_0.0.1_darwin_amd64.tar.gz"
      sha256 "c45a37f36a9a9926c714e8cd9ef0364366256d58773e4c0d7d6cd321dfeec7a5"

      def install
        bin.install "tactician"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/tactician/releases/download/v0.0.1/tactician_0.0.1_darwin_arm64.tar.gz"
      sha256 "b6398d39316899d8be8a0b413f6451925355bce1059270088bd629fb4d0ce61d"

      def install
        bin.install "tactician"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/tactician/releases/download/v0.0.1/tactician_0.0.1_linux_amd64.tar.gz"
      sha256 "b2795664860187a3427e82aed1d4b888c2dca1b2039d470fc85f9788ce540b4a"
      def install
        bin.install "tactician"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/tactician/releases/download/v0.0.1/tactician_0.0.1_linux_arm64.tar.gz"
      sha256 "1f742e4bf23b4f4478fc178c5eb49a641ca944d90a0ee9cd58301011077f71e8"
      def install
        bin.install "tactician"
      end
    end
  end
end
