# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uhoh < Formula
  desc "uhoh is a tool to build TUI forms and wizards"
  homepage "https://github.com/go-go-golems/uhoh"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/uhoh/releases/download/v0.0.5/uhoh_0.0.5_darwin_amd64.tar.gz"
      sha256 "098de090061e597f02cbd6e440fb4a66c3b889a723ea34fae3d64306e85cdb34"

      def install
        bin.install "uhoh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/uhoh/releases/download/v0.0.5/uhoh_0.0.5_darwin_arm64.tar.gz"
      sha256 "1b7e03fc8e6eb7856d2b4a9907a9e2e7f34f06304bbfbc24d74da0f885641f47"

      def install
        bin.install "uhoh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/uhoh/releases/download/v0.0.5/uhoh_0.0.5_linux_amd64.tar.gz"
      sha256 "547ea9879bbf0710235453e4c8f656673209b8d4912843e40cbdf55cfdaea136"
      def install
        bin.install "uhoh"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/uhoh/releases/download/v0.0.5/uhoh_0.0.5_linux_arm64.tar.gz"
      sha256 "88ec3fe42a92661209c2856bd6f0949b0f5b7d2c254bd8a8a92a4ac280340c98"
      def install
        bin.install "uhoh"
      end
    end
  end
end
