# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uhoh < Formula
  desc "uhoh is a tool to build TUI forms and wizards"
  homepage "https://github.com/go-go-golems/uhoh"
  version "0.0.2"

  on_macos do
    on_intel do
      url "https://github.com/go-go-golems/uhoh/releases/download/v0.0.2/uhoh_0.0.2_darwin_amd64.tar.gz"
      sha256 "f84fdc928a7dbd8bb17084fbae2731142d6f55638a66357dc27ad1b9c7892004"

      def install
        bin.install "uhoh"
      end
    end
    on_arm do
      url "https://github.com/go-go-golems/uhoh/releases/download/v0.0.2/uhoh_0.0.2_darwin_arm64.tar.gz"
      sha256 "ff2c0f7cc27db5b314bba996aee53f644ce8ff9d7b19e50ebf9f9513c68b771d"

      def install
        bin.install "uhoh"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-go-golems/uhoh/releases/download/v0.0.2/uhoh_0.0.2_linux_amd64.tar.gz"
        sha256 "97059d260ce389d50112876b2319f9901a2e67f8cc7cab370e0c8ce02167481d"

        def install
          bin.install "uhoh"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-go-golems/uhoh/releases/download/v0.0.2/uhoh_0.0.2_linux_arm64.tar.gz"
        sha256 "c01927bbc1894aced186a910b7d7da00b2e015800db8535e03269e05c1678642"

        def install
          bin.install "uhoh"
        end
      end
    end
  end
end
