# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VaultEnvrcGenerator < Formula
  desc "vault-envrc-generator is a tool"
  homepage "https://github.com/go-go-golems/vault-envrc-generator"
  version "0.0.15"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/vault-envrc-generator/releases/download/v0.0.15/vault-envrc-generator_0.0.15_darwin_amd64.tar.gz"
      sha256 "e614559634f07858c70a6f83711186ae5b85fd631f0d5a0673f866dec267b54d"

      def install
        bin.install "vault-envrc-generator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/vault-envrc-generator/releases/download/v0.0.15/vault-envrc-generator_0.0.15_darwin_arm64.tar.gz"
      sha256 "73e8be25c534cfa89a4854c82694db5683fbfe6469c369549fffd43ad0ebdf5a"

      def install
        bin.install "vault-envrc-generator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/vault-envrc-generator/releases/download/v0.0.15/vault-envrc-generator_0.0.15_linux_amd64.tar.gz"
      sha256 "b542a2bce3d5662b9e4a5bbe1ca8dd4b94a5426b6528df58cc15444707923c0b"
      def install
        bin.install "vault-envrc-generator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/vault-envrc-generator/releases/download/v0.0.15/vault-envrc-generator_0.0.15_linux_arm64.tar.gz"
      sha256 "c5731197d3c4cc891b06bf03193a04e5ad25ec08630b5f3ac5ebe0d7aa80a4d2"
      def install
        bin.install "vault-envrc-generator"
      end
    end
  end
end
