# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VaultEnvrcGenerator < Formula
  desc "vault-envrc-generator is a tool"
  homepage "https://github.com/go-go-golems/vault-envrc-generator"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/vault-envrc-generator/releases/download/v0.0.1/vault-envrc-generator_0.0.1_darwin_amd64.tar.gz"
      sha256 "4f8e73fd48f5226d48caa976b4cdcdc680786878052a31f5836ceee521edd379"

      def install
        bin.install "vault-envrc-generator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/vault-envrc-generator/releases/download/v0.0.1/vault-envrc-generator_0.0.1_darwin_arm64.tar.gz"
      sha256 "047f16aee64bfa14e5b15f842d549087c0173d39d58d6df8e82957908ffb3d1d"

      def install
        bin.install "vault-envrc-generator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/vault-envrc-generator/releases/download/v0.0.1/vault-envrc-generator_0.0.1_linux_amd64.tar.gz"
      sha256 "1783b6f8cc523a782067e36e7a6eab7e57315e710749faf415530f202b3bf21d"
      def install
        bin.install "vault-envrc-generator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/vault-envrc-generator/releases/download/v0.0.1/vault-envrc-generator_0.0.1_linux_arm64.tar.gz"
      sha256 "114752128c75de800c723fc5d3946b484665cf6ab45c56a9629c90a6ba08e0bb"
      def install
        bin.install "vault-envrc-generator"
      end
    end
  end
end
