# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wsm < Formula
  desc "wsm is a tool"
  homepage "https://github.com/go-go-golems/workspace-manager"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/workspace-manager/releases/download/v0.1.1/wsm_0.1.1_darwin_amd64.tar.gz"
      sha256 "dd2e8d97f71902805990c78b44727acf1706cc1b742412807a7d902bdaeb384d"

      define_method(:install) do
        bin.install "wsm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/workspace-manager/releases/download/v0.1.1/wsm_0.1.1_darwin_arm64.tar.gz"
      sha256 "63234e1d6932cf7b90b419a202b02cd5b5d881396b792430130beddf0d8b369d"

      define_method(:install) do
        bin.install "wsm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/workspace-manager/releases/download/v0.1.1/wsm_0.1.1_linux_amd64.tar.gz"
      sha256 "bb9ddbea03c081397afbfa85a5746cd3ce5645d85e91c99580967b4ec1e82064"
      define_method(:install) do
        bin.install "wsm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/workspace-manager/releases/download/v0.1.1/wsm_0.1.1_linux_arm64.tar.gz"
      sha256 "57f27b8ddf5e58ff4021656f92f3e222eca7fb30071b7bd3059d1592a37727a3"
      define_method(:install) do
        bin.install "wsm"
      end
    end
  end
end
