# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wsm < Formula
  desc "wsm is a tool"
  homepage "https://github.com/go-go-golems/workspace-manager"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/workspace-manager/releases/download/v0.2.1/wsm_0.2.1_darwin_amd64.tar.gz"
      sha256 "33429fab79dcb32a2f6941e54cc85449090d4da44aefb12b1d48e7c09b994445"

      define_method(:install) do
        bin.install "wsm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/workspace-manager/releases/download/v0.2.1/wsm_0.2.1_darwin_arm64.tar.gz"
      sha256 "96fea8b885bf5cae2491cf44f3c04e355d52bd9fc755f8ded51c4458a3f70dcc"

      define_method(:install) do
        bin.install "wsm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/workspace-manager/releases/download/v0.2.1/wsm_0.2.1_linux_amd64.tar.gz"
      sha256 "bef713c524811c9ef2d0c9661b1f42aa3273a65c8cf5092d5fddc57b8785d9ef"
      define_method(:install) do
        bin.install "wsm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/workspace-manager/releases/download/v0.2.1/wsm_0.2.1_linux_arm64.tar.gz"
      sha256 "71bfbcf22a340a2470e9a5bcc14b22bd0a43fa922c3c99c38617ca7ab23aeff1"
      define_method(:install) do
        bin.install "wsm"
      end
    end
  end
end
