# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wsm < Formula
  desc "wsm is a tool"
  homepage "https://github.com/go-go-golems/workspace-manager"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/workspace-manager/releases/download/v0.2.0/wsm_0.2.0_darwin_amd64.tar.gz"
      sha256 "b6c5c2a9f72e25ef813f4364ab0383d2264f89a9175a0b03222615e47ec05df6"

      define_method(:install) do
        bin.install "wsm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/workspace-manager/releases/download/v0.2.0/wsm_0.2.0_darwin_arm64.tar.gz"
      sha256 "d63b61743129fd1bd5c8c8ff68887995b4132bf63c39978893936151ce044983"

      define_method(:install) do
        bin.install "wsm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/workspace-manager/releases/download/v0.2.0/wsm_0.2.0_linux_amd64.tar.gz"
      sha256 "8e1000f1feb2c63c15d3511fd8c7e723ef71a43dda4e6c0106d7777beb37017b"
      define_method(:install) do
        bin.install "wsm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/workspace-manager/releases/download/v0.2.0/wsm_0.2.0_linux_arm64.tar.gz"
      sha256 "c1503d929b0ca185853d433b68e559cf8ae08d2116e8b7086f64ac975b4230a7"
      define_method(:install) do
        bin.install "wsm"
      end
    end
  end
end
