# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xxx < Formula
  desc "XXX is a tool"
  homepage "https://github.com/go-go-golems/XXX"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/goja-git/releases/download/v0.0.1/XXX_0.0.1_darwin_amd64.tar.gz"
      sha256 "85c74989a76465b4762a94c13ed23558af8ca9756d8aa448b4a56186b5e5515d"

      define_method(:install) do
        bin.install "XXX"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/goja-git/releases/download/v0.0.1/XXX_0.0.1_darwin_arm64.tar.gz"
      sha256 "281366cab02e2ce217f698a2a429382b00a04bcddf7404c419c5742f63093a14"

      define_method(:install) do
        bin.install "XXX"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/goja-git/releases/download/v0.0.1/XXX_0.0.1_linux_amd64.tar.gz"
      sha256 "ce70044190988baf03ae49f893aa97c1b66722c6dd7490f10ee1c79c1cf0793a"
      define_method(:install) do
        bin.install "XXX"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/goja-git/releases/download/v0.0.1/XXX_0.0.1_linux_arm64.tar.gz"
      sha256 "34983955359899af502621b431112bb04ee23dde21455766e2de2422d07e71bd"
      define_method(:install) do
        bin.install "XXX"
      end
    end
  end
end
