# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xxx < Formula
  desc "XXX is a tool"
  homepage "https://github.com/go-go-golems/XXX"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-go-golems/goja-git/releases/download/v0.0.2/XXX_0.0.2_darwin_amd64.tar.gz"
      sha256 "70ef0977fa79652995386cdc4cdca06f3c366c0112393f42d7389e1050e4e4d2"

      define_method(:install) do
        bin.install "XXX"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-go-golems/goja-git/releases/download/v0.0.2/XXX_0.0.2_darwin_arm64.tar.gz"
      sha256 "71d4d5494b4f525811d6b7a063ed0e0bc8ff8b5a11e8e4fd610014e9d664c72a"

      define_method(:install) do
        bin.install "XXX"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/goja-git/releases/download/v0.0.2/XXX_0.0.2_linux_amd64.tar.gz"
      sha256 "7436d292cc942304100abde38bf1014dabb6456f949e0b3627cd25699951efd3"
      define_method(:install) do
        bin.install "XXX"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-go-golems/goja-git/releases/download/v0.0.2/XXX_0.0.2_linux_arm64.tar.gz"
      sha256 "fa7c4c37b811e445f16534c3ee6a7a77c8a702349562ca2196891b807e821e90"
      define_method(:install) do
        bin.install "XXX"
      end
    end
  end
end
