# This file was generated by GoReleaser. DO NOT EDIT.
cask "devmesh" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "7d7a047da5004f04ae0fb46d7f409afe7c0be5493862abb20c8be60de0655cb1"
      url "https://github.com/go-go-golems/devmesh/releases/download/v#{version}/devmesh_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e9b90a19a902fca5150857d9894b01839e1f24f93f2a846353c91523f705696d"
      url "https://github.com/go-go-golems/devmesh/releases/download/v#{version}/devmesh_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2517323c36334a20bedacce5a4befe26c083486e97505c83df43c2e54bf96910"
      url "https://github.com/go-go-golems/devmesh/releases/download/v#{version}/devmesh_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a1eb3268efd50a5e9683ac34667a9cba7b358dc7be1940e71e3719491b113c84"
      url "https://github.com/go-go-golems/devmesh/releases/download/v#{version}/devmesh_#{version}_linux_amd64.tar.gz"
    end
  end

  name "devmesh"
  desc "Stable local endpoints for ephemeral development service backends"
  homepage "https://github.com/go-go-golems/devmesh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devmesh"
  binary "devmeshd"

  # No zap stanza required
end
