# This file was generated by GoReleaser. DO NOT EDIT.
cask "goja-dbus" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "fc4294a5b05bc6809010941b125ca017f6776f2b512eedd0e55e5ab8f32c05c4"
      url "https://github.com/go-go-golems/goja-dbus/releases/download/v#{version}/goja-dbus_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8ba089fcfc85a7d2f7a5101b393296ac3f4832dd6bba3f4d7a623c324b3ac854"
      url "https://github.com/go-go-golems/goja-dbus/releases/download/v#{version}/goja-dbus_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "95a62e9671e84541a1e19dbbb522cdae952271809707ac3caa7a8aed5bade069"
      url "https://github.com/go-go-golems/goja-dbus/releases/download/v#{version}/goja-dbus_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3df7c54d72999613e794af78a10c23d556cc457796902064cb58961e41737889"
      url "https://github.com/go-go-golems/goja-dbus/releases/download/v#{version}/goja-dbus_#{version}_linux_arm64.tar.gz"
    end
  end

  name "goja-dbus"
  desc "goja-dbus is a go-go-goja native D-Bus module and xgoja CLI"
  homepage "https://github.com/go-go-golems/goja-dbus"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goja-dbus"

  # No zap stanza required

end
