# This file was generated by GoReleaser. DO NOT EDIT.
cask "goja-dbus" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "88b141c5fa12a54b66dd5a29112cd7612c1e513703b7f347481a9bc35bb8f8db"
      url "https://github.com/go-go-golems/goja-dbus/releases/download/v#{version}/goja-dbus_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9a7b1c47dfadd15a7ccaa6a06914ebe62f447ab7b3848e896b8ee3017d8a13e2"
      url "https://github.com/go-go-golems/goja-dbus/releases/download/v#{version}/goja-dbus_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2353133f479dc9b95d08c4d13d7e85de6212704fe8978d02100d231621dc6af1"
      url "https://github.com/go-go-golems/goja-dbus/releases/download/v#{version}/goja-dbus_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "72592670417ce16a6875c22af3e1a87d4537fe1437686413e560381b079a1b5e"
      url "https://github.com/go-go-golems/goja-dbus/releases/download/v#{version}/goja-dbus_#{version}_linux_arm64.tar.gz"
    end
  end

  name "goja-dbus"
  desc "goja-dbus is a go-go-goja native D-Bus module and xgoja CLI"
  homepage "https://github.com/go-go-golems/goja-dbus"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goja-dbus"

  # No zap stanza required

end
