# This file was generated by GoReleaser. DO NOT EDIT.
cask "loupedeck" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "a1dd0f38877df10943ece56a21451887ae5a8c19137e175a1e6154f3ab09bcbf"
      url "https://github.com/go-go-golems/loupedeck/releases/download/v#{version}/loupedeck_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b6e36979020d4f4f90ace85529eb3d5688f4c39deeeb0114900b7ce0dac5ca3c"
      url "https://github.com/go-go-golems/loupedeck/releases/download/v#{version}/loupedeck_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cf3e53a428ced156eb3fa46cc9dabfadf86411743d2207fb98e0854d0bb77649"
      url "https://github.com/go-go-golems/loupedeck/releases/download/v#{version}/loupedeck_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b8019f1ca42935af36b279309f85989ec60a4781ad95fd5df297e6ee7e0e202d"
      url "https://github.com/go-go-golems/loupedeck/releases/download/v#{version}/loupedeck_#{version}_linux_arm64.tar.gz"
    end
  end

  name "loupedeck"
  desc "Run Loupedeck Live JavaScript scenes and hardware workflows"
  homepage "https://github.com/go-go-golems/loupedeck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loupedeck"

  # No zap stanza required

end
