# This file was generated by GoReleaser. DO NOT EDIT.
cask "loupedeck" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "4fd1e4bb1d9b7abee624171fb5c357b972d1e00a477acfd2aa211a9a692f61c2"
      url "https://github.com/go-go-golems/loupedeck/releases/download/v#{version}/loupedeck_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4bf6f63ef7a59c97f5d6b85eb8afeeabd91d492006aad9c94ec53b2e4459380a"
      url "https://github.com/go-go-golems/loupedeck/releases/download/v#{version}/loupedeck_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d9145df5d3071a1c311812b7e1a971a5394cc08158ad7415b2624323c1578a2c"
      url "https://github.com/go-go-golems/loupedeck/releases/download/v#{version}/loupedeck_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f4dcca593c248a5d64fee1f09d33f5c5033f838ed5f56cb8ace7ec7eeb83f46f"
      url "https://github.com/go-go-golems/loupedeck/releases/download/v#{version}/loupedeck_#{version}_linux_arm64.tar.gz"
    end
  end

  name "loupedeck"
  desc "Run Loupedeck Live JavaScript scenes and hardware workflows"
  homepage "https://github.com/go-go-golems/loupedeck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loupedeck"

  # No zap stanza required

end
