# This file was generated by GoReleaser. DO NOT EDIT.
cask "loupedeck" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "6819c1af9c6af4e9a686bd7a1172be397a52f4b9e950eea3727481f4f5b8e7be"
      url "https://github.com/go-go-golems/loupedeck/releases/download/v#{version}/loupedeck_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2dd70a1f4beb006fa4ee467d817b7ac86b1f3fa08b1b2c4aa17889c72154280a"
      url "https://github.com/go-go-golems/loupedeck/releases/download/v#{version}/loupedeck_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6782758eae67159854428355e64d9b42c4ca829c2682a9b997d33d40d66164b6"
      url "https://github.com/go-go-golems/loupedeck/releases/download/v#{version}/loupedeck_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "83a5506a491345b92d02abe7b88dffdb311c11efd6b4c9b4cb0556b8126af413"
      url "https://github.com/go-go-golems/loupedeck/releases/download/v#{version}/loupedeck_#{version}_linux_arm64.tar.gz"
    end
  end

  name "loupedeck"
  desc "Run Loupedeck Live JavaScript scenes and hardware workflows"
  homepage "https://github.com/go-go-golems/loupedeck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loupedeck"

  # No zap stanza required

end
