# This file was generated by GoReleaser. DO NOT EDIT.
cask "openai-app-server" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "d5b0f50f34a4a4f02660be2cb65def485b07ed6628cc45d3125d85dbbbd06a26"
      url "https://github.com/go-go-golems/openai-app-server/releases/download/v#{version}/openai-app-server_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fcaf43d6ea4c38790a180aa49c2efb149f86d297be9ca045c78b36f4b1ca0d12"
      url "https://github.com/go-go-golems/openai-app-server/releases/download/v#{version}/openai-app-server_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "26c6b5504bd652d49fd8cbd5538130ab1e29acc974242df7c39144cc4a7b1241"
      url "https://github.com/go-go-golems/openai-app-server/releases/download/v#{version}/openai-app-server_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ce08b4fb2b19ff807b7f1e5979cfa73be5a828433833b9ed738ab745915cf0c6"
      url "https://github.com/go-go-golems/openai-app-server/releases/download/v#{version}/openai-app-server_#{version}_linux_arm64.tar.gz"
    end
  end

  name "openai-app-server"
  desc "JSON-RPC JS harness runtime for OpenAI Codex app-server workflows"
  homepage "https://github.com/go-go-golems/openai-app-server"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openai-app-server"

  # No zap stanza required

end
