# This file was generated by GoReleaser. DO NOT EDIT.
cask "tinyidp" do
  version "0.0.5"

  on_macos do
    on_intel do
      sha256 "526dad527b180c8bd52f1c0cad5c605ffa268ac13ec9eee5b78eb5e63ef0f3d8"
      url "https://github.com/go-go-golems/tiny-idp/releases/download/v#{version}/tinyidp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5bca96117f2128ae7387d830cbc1ea7a554978cf52379c00fc0fdfb44cd79087"
      url "https://github.com/go-go-golems/tiny-idp/releases/download/v#{version}/tinyidp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "90f744e55ee9f2e3e97886b2ce5dae2109c4a82ce2792c3178250f05b8478334"
      url "https://github.com/go-go-golems/tiny-idp/releases/download/v#{version}/tinyidp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "adaec0b6aec0568576d163dcbfc7f4c9749347b41e266660c75646bb16f10bca"
      url "https://github.com/go-go-golems/tiny-idp/releases/download/v#{version}/tinyidp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tinyidp"
  desc "tinyidp is a compact, self-contained OpenID Connect Identity Provider."
  homepage "https://github.com/go-go-golems/tiny-idp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tinyidp"

  # No zap stanza required

end
