# This file was generated by GoReleaser. DO NOT EDIT.
cask "tinyidp" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "8d3b73d7219b6bbbfc34dc8c1f8304c5af3c488b0485667e432b735e434d691c"
      url "https://github.com/go-go-golems/tiny-idp/releases/download/v#{version}/tinyidp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "49a4bf32eeb5eeb034293de92be82b5d83a59187e3cf1f91478c7b561347e838"
      url "https://github.com/go-go-golems/tiny-idp/releases/download/v#{version}/tinyidp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "eee9e09bd2baf1ae955563095f2cd8d7dd23865973e6d0dfd7291d12d6049874"
      url "https://github.com/go-go-golems/tiny-idp/releases/download/v#{version}/tinyidp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d7a339d23a1da42fb2f78b3e2cfd894aaedc0eb1cc6e94ada644f571d0c6b412"
      url "https://github.com/go-go-golems/tiny-idp/releases/download/v#{version}/tinyidp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tinyidp"
  desc "tinyidp is a compact, self-contained OpenID Connect Identity Provider."
  homepage "https://github.com/go-go-golems/tiny-idp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tinyidp"

  # No zap stanza required

end
