# This file was generated by GoReleaser. DO NOT EDIT.
cask "tinyidp" do
  version "0.0.4"

  on_macos do
    on_intel do
      sha256 "c302182d2c3293ead1168eb5cdadb381db4ba74880263612f03f533ae88a0c83"
      url "https://github.com/go-go-golems/tiny-idp/releases/download/v#{version}/tinyidp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2b7363bdb4be380b41f353ce9e4a916b84deaa12bd5d78f251e0036df107a5f2"
      url "https://github.com/go-go-golems/tiny-idp/releases/download/v#{version}/tinyidp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "25eeeeb24253943710c2a2c602859b2ab09251f05ddc72ae1b993751b50664bb"
      url "https://github.com/go-go-golems/tiny-idp/releases/download/v#{version}/tinyidp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "30588427d11ead35f3d1ce935172a67ab8525aa3583273c50d408ae9d1f355f6"
      url "https://github.com/go-go-golems/tiny-idp/releases/download/v#{version}/tinyidp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tinyidp"
  desc "tinyidp is a compact, self-contained OpenID Connect Identity Provider."
  homepage "https://github.com/go-go-golems/tiny-idp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tinyidp"

  # No zap stanza required

end
